#!/usr/bin/env python3
"""
Development server that reads .env and generates env.js before serving.
"""

import http.server
import socketserver
import os

PORT = 8001
ENV_FILE = ".env"
ENV_JS_PATH = "assets/config/env.js"


def load_env():
    """Read .env file and return dict of values."""
    env = {}
    if not os.path.exists(ENV_FILE):
        print(f"Warning: {ENV_FILE} not found. Copy .env.example to .env and add your keys.")
        return env

    with open(ENV_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                env[key.strip()] = value.strip()
    return env


def generate_env_js(env):
    """Generate env.js file from environment variables."""
    os.makedirs(os.path.dirname(ENV_JS_PATH), exist_ok=True)

    with open(ENV_JS_PATH, "w") as f:
        f.write("// Auto-generated by serve.py - do not edit directly\n")
        f.write("// Edit .env instead and restart the server\n\n")
        f.write("window.ENV = {\n")
        f.write(f"    LOGO_DEV_TOKEN: '{env.get('LOGO_DEV_TOKEN', '')}',\n")
        f.write(f"    LOGO_DEV_SECRET: '{env.get('LOGO_DEV_SECRET', '')}'\n")
        f.write("};\n")

    print(f"Generated {ENV_JS_PATH}")


def main():
    # Load .env and generate env.js
    env = load_env()
    generate_env_js(env)

    # Start HTTP server
    handler = http.server.SimpleHTTPRequestHandler
    with socketserver.TCPServer(("", PORT), handler) as httpd:
        print(f"Serving at http://localhost:{PORT}")
        print("Press Ctrl+C to stop")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nShutting down...")


if __name__ == "__main__":
    main()
